on:
  push:

jobs:
  release-apax-lib:
    uses: simatic-ax/actions/.github/workflows/apax-export-tialib.yml@stable
    secrets:
      APAX_TOKEN: ${{ secrets.APAX_TOKEN }}
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

    with:
      VERSION: ${{ github.ref_name }}
      PROJECT_NAME: ae-tiax